language: node_js
sudo: false
node_js:
  - '4.2.1'

cache:
  directories:
    - node_modules

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - du -sh ./node_modules || true
  - npm install

before_script:
  - ./node_modules/.bin/jspm config registries.github.auth $GH_TOKEN
  - ./node_modules/.bin/jspm install
  - chmod +x ./scripts/ci/build_and_test.sh

script:
  - ./scripts/ci/build_and_test.sh