language: node_js
sudo: false
node_js:
  - 'stable'

notifications:
  email: false

cache:
  directories:
    - node_modules

branches:
  only:
    - master

install:
  - npm install

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run test:jest
  - npm run coverage
