language: node_js
sudo: false
node_js:
  - "0.12"

cache:
  directories:
    - node_modules

install:
  - du -sh ./node_modules || true
  - npm config set spin false
  - npm config set loglevel http
  - npm install -g npm@2.5
  - npm install

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

before_script:
  - ./node_modules/.bin/jspm config registries.github.auth $GH_TOKEN
  - ./node_modules/.bin/jspm install